- hosts: localhost
  connection: local
  become: true

  pre_task:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/ubuntu/packages.yml
