---
- hosts: localhost
  become: true

  tasks:
    - name: install neofetch
      package:
        name:
          - neofetch
          - htop
          - tmux
          - docker
          - vim-nox
